[theme]
primaryColor = "#002855"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFB81C"
textColor = "#212529"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
